# For more information: https://elephox.dev/ecosystem/plane
version: '3'
services:
    elephox:
        build:
            context: ./vendor/elephox/plane/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            ELEPHOX_PLANE: 1
            XDEBUG_MODE: '${PLANE_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${PLANE_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - plane
networks:
    plane:
        driver: bridge
