# For more information: https://github.com/elephox-dev/plane
version: '3'
services:
    elephox:
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8000}:8000'
        environment:
            WWWUSER: '${WWWUSER}'
            ELEPHOX_PLANE: 1
            XDEBUG_MODE: '${PLANE_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${PLANE_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - plane
networks:
    plane:
        driver: bridge
